[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'tests/foundry'
cache_path = 'cache_forge'
ignored_warnings_from = ["tests/"]
optimizer = true
optimizer_runs = 200
solc_version = '0.8.23'
show_progress = true
fs_permissions = [{ access = "read-write", path = "./"}]
ignored_error_codes = [3628]
remappings = [
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    'solady/=lib/solady/src/',
]
gas_limit = "18446744073709551615"

[rpc_endpoints]
sepolia = "${ARB_SEPOLIA}"

[etherscan]
sepolia = { key = "${ETHERSCAN_KEY}", url = "https://api-sepolia.etherscan.io/api" }

[fmt]
line_length = 100

[fuzz]
runs = 256