[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'tests/foundry'
cache_path = 'cache_forge'
optimizer = true
optimizer_runs = 200
solc_version = '0.8.23'
fs_permissions = [{ access = "read-write", path = "./"}]

[fmt]
line_length = 100